name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7  
    - name: Format with Black Code Formatter
      uses: lgeiger/black-action@v1.0.1
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-line-length=127 --statistics
    - name: Build
      run: |
        pip install .
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Create source distributions 
      run: |
        python setup.py sdist
