name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7  
    - name: Build
      run: |
        pip install .
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Create source distributions 
      run: |
        python setup.py sdist
        # from https://github.com/marketplace/actions/autopep8
    - name: autopep8
      id: autopep8
      uses: peter-evans/autopep8@v1.1.0
      with:
        args: --exit-code --recursive --in-place --aggressive --aggressive .
    - name: Commit autopep8 changes
      if: steps.autopep8.outputs.exit-code == 2
      run: |
        git config --global user.name 'Felix Andreas'
        git config --global user.email 'felix.andreas95@googlemail.com'
        git remote set-url origin https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Automated autopep8 fixes"
        git push
  

