name: CI

on: [push]

jobs:
  build:
    name: Build and Test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Build and install
      run: |
        pip install .
    - name: Create source distributions
      run: |
        python setup.py sdist
    - name: Test with pytest
      run: |
        pip install pytest
        pytest

# from https://github.com/marketplace/actions/autopep8
  autopep8:
    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
    - name: Autoformat with autopep8
      id: autopep8
      uses: peter-evans/autopep8@v1.1.0
      with:
        args: --exit-code --recursive --in-place --aggressive --aggressive .
    - name: Commit autopep8 changes
      if: steps.autopep8.outputs.exit-code == 2
      run: |
        git config --global user.name 'Felix Andreas'
        git config --global user.email 'felix.andreas95@googlemail.com'
        git remote set-url origin https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/${{ github.repository }}
        git commit -am "Automated autopep8 fixes"
        git push
  

