name: Share data between jobs

on: [push]

jobs:
  build:
    name: Build and Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build and install
        run: |
          pip install .
      - name: Create source distributions
        run: |
          python setup.py sdist
      - name: Test with pytest
        run: |
          pip install pytest
          pytest

  lint:
    name: Lint and Autoformat
    needs: build

    # Check if the PR is not from a fork
    if: github.event.pull_request.head.repo.full_name == github.repository

    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: |
          expr 3 + 7 > math-homework.txt
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: math-homework.txt